[kde]
kde_color_file_path1=/home/yian/.local/share/color-schemes/dynamic_color.colors
kde_color_file_path2=/home/yian/.local/share/color-schemes/My_dark_color.colors
color_map_file=/home/yian/Code/kde-coherent-color/kde-coherent-color-scheme/shell/color-config.txt
# dycolor 配置文件
# 第一行指定目标.colors文件的绝对路径
[dycolor]
# pywal 颜色文件
wal=/home/yian/.cache/wal/colors
poll_interval_seconds=3

